# Basic
title: Onefishcycle
subtitle: 鱼翔浅底的博客
welcome_message: <a href="https://github.com/csyuxuan/myblog" target="_blank">My GitHub repository.</a>
description: 每天更新一篇：读书笔记、生活感悟……
creator: <a href="http://onefishcycle.com">@onefishcycle</a>

url: "http://onefishcycle.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
# nav:
    # - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
# comment:
    # disqus: vno-jekyll
    # duoshuo: 
    
# Social
#social:
    # weibo: onevcat
    # github: onevcat
    # twitter: onevcat
    # gplus: 107108267983477358170
    # mail: onev@onevcat.com

# Google Analytics
#ga:
    # id: your_ga_id
    # host: your_host

theme: minimal-mistakes-jekyll